// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.2
// source: proto/beatroute/dms/example.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "../common/empty";
import { Pagination } from "../common/response";

export const protobufPackage = "beatroute.dms";

export interface ExampleRequestDto {
  name: string;
  description: string;
}

export interface Example {
  id: number;
  name: string;
  description: string;
}

export interface ExampleViewRequestDto {
  id: number;
}

export interface ExampleDeleteRequestDto {
  id: number;
}

export interface ExampleListRequestDto {
  page?: number | undefined;
}

export interface ExampleResponseListDto {
  examples: Example[];
  pagination: Pagination | undefined;
}

export const BEATROUTE_DMS_PACKAGE_NAME = "beatroute.dms";

export interface ExampleServiceClient {
  create(request: ExampleRequestDto): Observable<Example>;

  index(request: ExampleListRequestDto): Observable<ExampleResponseListDto>;

  view(request: ExampleViewRequestDto): Observable<Example>;

  delete(request: ExampleDeleteRequestDto): Observable<Empty>;
}

export interface ExampleServiceController {
  create(request: ExampleRequestDto): Promise<Example> | Observable<Example> | Example;

  index(
    request: ExampleListRequestDto,
  ): Promise<ExampleResponseListDto> | Observable<ExampleResponseListDto> | ExampleResponseListDto;

  view(request: ExampleViewRequestDto): Promise<Example> | Observable<Example> | Example;

  delete(request: ExampleDeleteRequestDto): Promise<Empty> | Observable<Empty> | Empty;
}

export function ExampleServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create", "index", "view", "delete"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ExampleService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ExampleService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EXAMPLE_SERVICE_NAME = "ExampleService";
