// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.2
// source: proto/beatroute/dms/health.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "beatroute.dms";

export interface HealthCheckRequest {
}

export interface HealthCheckResponse {
  status: boolean;
}

export const BEATROUTE_DMS_PACKAGE_NAME = "beatroute.dms";

export interface HealthServiceClient {
  checkHealth(request: HealthCheckRequest): Observable<HealthCheckResponse>;
}

export interface HealthServiceController {
  checkHealth(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;
}

export function HealthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkHealth"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("HealthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("HealthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const HEALTH_SERVICE_NAME = "HealthService";
