// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.2
// source: proto/beatroute/dms/meta.proto

/* eslint-disable */

export const protobufPackage = "beatroute.dms";

export interface Meta {
  currentPage: number;
  totalCount: number;
  perPage: number;
  pageCount: number;
}

export const BEATROUTE_DMS_PACKAGE_NAME = "beatroute.dms";
