// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.2
// source: proto/beatroute/auth/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "beatroute.auth";

export interface AuthenticateRequestDto {
  token: string;
}

export interface AuthenticateResponseDto {
  jwtToken: string;
}

export const BEATROUTE_AUTH_PACKAGE_NAME = "beatroute.auth";

export interface AuthServiceClient {
  authenticate(request: AuthenticateRequestDto): Observable<AuthenticateResponseDto>;
}

export interface AuthServiceController {
  authenticate(
    request: AuthenticateRequestDto,
  ): Promise<AuthenticateResponseDto> | Observable<AuthenticateResponseDto> | AuthenticateResponseDto;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["authenticate"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
