// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.2
// source: proto/beatroute/common/response.proto

/* eslint-disable */
import { Any } from "../../../google/protobuf/any";

export const protobufPackage = "beatroute.common";

export interface Response {
  success: boolean;
  status: number;
  message: string;
  data?: Any | undefined;
  dataError?: Any | undefined;
  pagination?: Pagination | undefined;
}

export interface Pagination {
  currentPage: number;
  totalCount: number;
  perPage: number;
  pageCount: number;
}

export const BEATROUTE_COMMON_PACKAGE_NAME = "beatroute.common";
