// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.2
// source: proto/beatroute/common/user-identity.proto

/* eslint-disable */

export const protobufPackage = "beatroute.common";

export interface UserIdentity {
  id: number;
  name: string;
  role: number;
  companyId: number;
}

export const BEATROUTE_COMMON_PACKAGE_NAME = "beatroute.common";
